language: node_js
node_js:
  - 'node' # use latest stable nodejs version
  - '6'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.2
script:
  - yarn build
  - yarn test
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
